### PR TITLE
Few fixes. Upgraded jsdox.

### PR DESCRIPTION
**Pull request by mrjoelkemp**
- Bumps JSDox to the latest version
- Adds support for the `templateDir` option (w/ updated readme)
- Updated `example` files against the latest output of JSDox.

cc @psq @boneskull

### CODE REVIEW

**Comment by boneskull** [comment]
:+1: works

**Comment by psq** [comment]
that's cool!

**Comment by mrjoelkemp** [comment]
@mmacmillan Any ideas when this can get merged? Cutting a new release afterward would be great.

**Comment by mmacmillan** [comment]
@mrjoelkemp @psq, ill take a look at the PR and merge.  I'm coming back from several months focus/deadline on a different project, but will be actively developing on this component again.  Ill add you guys as maintainers so we can streamline this process and keep it fresh.  I appreciate the help!

**Comment by mmacmillan** [comment]
merged, bumped version to 0.1.6

**Comment by mrjoelkemp** [comment]
+1 Thanks @mmacmillan

**Comment by psq** [comment]
thanks @mmacmillan

**Pull request merged**
